name: main CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build/libs/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build

      - name: Remove old build files
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          script: |
            chmod +x /home/ubuntu/delete_script.sh
            sudo /home/ubuntu/delete_script.sh

      - name: Run a multi-line script
        run: |
          mkdir ../build
          cp -TR . ../build
          tar -cvf deploy.tar ../build/

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ubuntu/deploy-jar"

      - name: Execute remote command via SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.AWS_EC2_USER }}
          key: ${{ secrets.AWS_EC2_KEY }}
          script: |
            chmod +x /home/ubuntu/deploy_script.sh
            sudo /home/ubuntu/deploy_script.sh