name: main CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: wake-up
          path: build/libs/wake-up-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: wake-up
          path: build/libs/

      - name: Copy files via SCP
        run: |
          echo "${{ secrets.AWS_EC2_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -o StrictHostKeyChecking=no build/libs/wake-up-0.0.1-SNAPSHOT.jar ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }}:/home/${{ secrets.AWS_EC2_USER }}/deploy-jar/wake-up.jar
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.AWS_EC2_USER }}@${{ secrets.AWS_EC2_HOST }} "pgrep java | xargs kill -9; nohup java -jar /home/${{ secrets.AWS_EC2_USER }}/deploy-jar/wake-up.jar > /home/{ secrets.AWS_EC2_USER }}/logs/app-\${date +'%Y%m%d%H%M%S'}.log 2>&1 &
          rm -f private_key.pem